### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Vianpyro** [Piaero/what2pick#14]
I tried to start your app, usign `npm start` and `yar start` none of them worked.
I'm not very good with NodeJS so I don't know how to fix this and see what is your code doing 😞.
![image](https://user-images.githubusercontent.com/10519369/103460553-19436100-4ce5-11eb-8855-111370fd0091.png)

The log file content:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'package.json'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle what2pick@1.0.0~prestart: what2pick@1.0.0
6 info lifecycle what2pick@1.0.0~start: what2pick@1.0.0
7 verbose lifecycle what2pick@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle what2pick@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user\Desktop\what2pick-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python39\;C:\Users\user\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python38-32\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\GitHubDesktop\bin;C:\Users\user\AppData\Local\Programs\Git\cmd;C:\Users\user\AppData\Roaming\npm
9 verbose lifecycle what2pick@1.0.0~start: CWD: C:\Users\user\Desktop\what2pick-master
10 silly lifecycle what2pick@1.0.0~start: Args: [ '/d /s /c', 'node backend/server.js "package.json"' ]
11 silly lifecycle what2pick@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle what2pick@1.0.0~start: Failed to exec start script
13 verbose stack Error: what2pick@1.0.0 start: `node backend/server.js "package.json"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid what2pick@1.0.0
15 verbose cwd C:\Users\user\Desktop\what2pick-master
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "package.json"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error what2pick@1.0.0 start: `node backend/server.js "package.json"`
22 error Exit status 1
23 error Failed at the what2pick@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Piaero** [comment]
Hello Vianpyro,
thank you for contacting me :)

First of all, I am starting the app with "yarn dev" but it doesn't seem to be a problem.

One of the first things the app does after launching is connecting to the database, but you don't have access to it because I didn't upload the creditentials to the database. 

If you want to check hosted app visit: https://what2pick.herokuapp.com/ (it's a free hosting, so sometimes it takes some time to load). The app presents most of the data I wanted it to show. Soon I will be working on the styling.

Feel free to message me if you have more questions.

**Comment by Vianpyro** [comment]
Thank you for answering to me so fast,

I do have one more question : where does your data come from?
I want to create an application like yours, but I can't find a way to get the data efficiently.
What I mean is where does the data in your database come from?

**Comment by Piaero** [comment]
I have done the database manually all by myself. It took long hours to analyse properties of all champions. This is the reason why I am keeping the database secret.

**Comment by Vianpyro** [comment]
Ok, thank you very much for you answer, good luck with your app, I'm glad I can use (your) help to choose what 2 pick in my solo queues :D

**Comment by Piaero** [comment]
Good luck in LoL :) Please tell me if you encounter a bug, in console you will find the "state" that was before the problem. It is my first app, so it may have some errors...

**Comment by Piaero** [comment]
I am happy to announce that with last commit I have reached MVP version :)
